export const URL_BASE_VERIFICATION = process.env.NEXT_PUBLIC_API_BANK;
export const URL_VERIFICATION_ENDPOINT =
  process.env.NEXT_PUBLIC_API_VERIFICATION;
export const API_CLIENT = process.env.NEXT_PUBLIC_USER_API_VERIFICATION;
export const API_SECRET_CLIENT = process.env.NEXT_PUBLIC_PASS_API_VERIFICATION;
export const WEB_BANK_URL = process.env.NEXT_PUBLIC_WEB_BANK